language: php
php:
  - 7.1

before_script:
  - composer install

addons:
  sonarcloud:
    organization: "rossedlin-github" # the key of the org you chose at step #3
    token:
      secure: da90c00d4fa8a067c4907d074fefa4e44abfd19d # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - vendor/phpunit/phpunit/phpunit
  - sonar-scanner



notifications:
  email:
    - travis-ci@rossedlin.com