language: php
php:
  - 7.1

before_script:
  - composer install

addons:
  sonarcloud:
    organization: "rossedlin-github" # the key of the org you chose at step #3
    token:
      secure: j6Oh1WMDWVrc4LxhGnsgjzRp6uf5TNVkFGk5xXbACLzgdLhOEiIfpJk/mfcHNTZW2NQ6WS/Ma/9dTjWW8xx/Y0cnZ9kAxYhaDUK9IFqAmR94ycWwFK9CxwmzNJ7CoNrT2BrlU+yiKXXypXoS78sDp5cRNZjV6qHm+WQV5WalieamKyR4LV7huIbcl08J1TeIs6AIsau/2slq/r3CO8jpFgI/IUjdqngFLZeEfps9+s8ffjqGyVXMzOvd89Vx9cVwYWv5kA5kZzyU32hBNoDXJUDo5u5GLbhXa/9yZI3HFEixyh/QnLRtqAWgC6zcXICNqI4WzisyInPzumKkLJlKTqDtEky76aQdF/JhqMbAly7TNpWY+GC9IV/JtM6xT9zasAhYLHxdtqxe3cQ2F47JS33O/dFCxm8tIhpzQdNoA+eOgmYFNZDO5EUAUWGYSfJiwQ6uhm54WE/a1AjABAfmhSRypO1hWu3H6+gB1yhOKa/HgrVrPa0/+gJZZJpancuhSEGqUDVIYd71mjoP/jQrrCjNBryBRGqKdGJEUSsslm0tpUacrxFRSZdkF04BkcFHVnskPtDumxvzIupPx5Q1h9k8vMiQAwupMggL1VzBbok7/wiSMZe+kNz4dFxakyA2PxMkwCGIqT/64wfS2eS+8LGfheseTRlx+XpN8pokGFo=
script:
  # other script steps might be done before running the actual analysis
  - vendor/phpunit/phpunit/phpunit
  - sonar-scanner



notifications:
  email:
    - travis-ci@rossedlin.com