name: Build

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest
    container:
      image: rossedlin/php-apache:7.1
    steps:
      - uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --colors=always
